USE [Lily_Repository]
GO
select * into [Lily_Repository].[Client_JOBTASK]
--insert into [Lily_Repository].[dbo].[Client_JOBTASK_DAF]
SELECT  [Job Plan][JPNUM]
      ,[Job Plan Task][JPTASK]
      ,[Description][DESCRIPTION]
      ,[Duration][TASKDURATION]
      ,null[JO1]
      ,null[JO2]
      ,null[JO3]
      ,null[JO4]
      ,null[JO5]
      ,null[JO6]
      ,null[JO7]
      ,null[JO8]
      ,[Organization][ORGID]
      ,[Site][SITEID]
      ,null[TASKSEQUENCE]
      ,null[METERNAME]
      ,null[JOBTASKID]
      --,null[JOBPLANID]
      ,null[LANGCODE]
      ,null[HASLD]
      ,null[NESTEDJPNUM]
      ,null[CLASSSTRUCTUREID]
      ,null[NESTEDJOBPLANID]
      ,null[OWNER]
      ,null[OWNERGROUP]
      ,null[FLOWACTION]
      ,null[FLOWCONTROLLED]
      ,null[SUSPENDFLOW]
      ,null[FLOWACTIONASSIST]
      ,null[LAUNCHENTRYNAME]
      ,null[PREDECESSORTASKS]
      ,null[ROWSTAMP]
      ,null[ASSIGNEDOWNERGROUP]
      ,null[CONDITIONNUM]
      ,[Revision][PLUSCJPREVNUM]
      ,null[PLUSCREVSTATUS]
      ,null[PLUSCNESTEDJPREVNUM]
      ,null[APPTREQUIRED]
      ,null[INCTASKSINSCHED]
      ,null[CREWWORKGROUP]
      ,null[HNAACTIVITY]
      ,null[INSPFORMNUM]
      ,null[INTSHIFT]
      ,null[INTERRUPTIBLE]
  FROM [Lilly_Straging].[dbo].[Asset Analytix Job Plan Task table] 
  where Site = 'DAF' and Status='active'

GO

select distinct Status from [Lilly_Straging].[dbo].[Asset Analytix Job Plan Task table]
select * from  [Lilly_Straging].[dbo].[Asset Ana[dbo].[Client_Locations_DAF]lytix Job Plan Task table] 

--truncate table [dbo].[Client_JOBTASK_]

