USE [Lily_Repository]
GO

insert into [Lily_Repository].[dbo].[Client_workorder_All] ( [WONUM]
      ,[PARENT]
      ,[STATUS]
      ,[STATUSDATE]
      ,[WORKTYPE]
      ,[DESCRIPTION]
      ,[ASSETNUM]
      ,[LOCATION]
      ,[JPNUM]
      ,[FAILDATE]
      ,[CHANGEDATE]
      ,[ESTDUR]
      ,[ESTLABHRS]
      ,[ESTMATCOST]
      ,[ESTLABCOST]
      ,[ESTTOOLCOST]
      ,[PMNUM]
      ,[ACTLABHRS]
      ,[ACTMATCOST]
      ,[ACTLABCOST]
      ,[HASCHILDREN]
      ,[REPORTEDBY]
      ,[HISTORYFLAG]
      ,[WOPRIORITY]
      ,[TARGCOMPDATE]
      ,[TARGSTARTDATE]
      ,[REPORTDATE]
      ,[DOWNTIME]
      ,[ACTSTART]
      ,[ACTFINISH]
      ,[SCHEDSTART]
      ,[SCHEDFINISH]
      ,[CREWID]
      ,[FAILURECODE]
      ,[SITEID]
      ,[CLASSSTRUCTUREID]
      ,[F37]
      ,[Year]
      ,[SPARECOST]
      ,[LABORCOST]
      ,[IsReview]
      ,[DEV_WORKTYPE]
      ,[CMDowntime]
      ,[PMDowntime]
      ,[RMDowntime]
      ,[NONPPMDowntime]
      ,[LDTEXT])
	  
select   [WONUM]
      ,[PARENT]
      ,[STATUS]
      ,[STATUSDATE]
      ,[WORKTYPE]
      ,[DESCRIPTION]
      ,[ASSETNUM]
      ,[LOCATION]
      ,[JPNUM]
      ,[FAILDATE]
      ,[CHANGEDATE]
      ,[ESTDUR]
      ,[ESTLABHRS]
      ,[ESTMATCOST]
      ,[ESTLABCOST]
      ,[ESTTOOLCOST]
      ,[PMNUM]
      ,[ACTLABHRS]
      ,[ACTMATCOST]
      ,[ACTLABCOST]
      ,[HASCHILDREN]
      ,[REPORTEDBY]
      ,[HISTORYFLAG]
      ,[WOPRIORITY]
      ,[TARGCOMPDATE]
      ,[TARGSTARTDATE]
      ,[REPORTDATE]
      ,[DOWNTIME]
      ,[ACTSTART]
      ,[ACTFINISH]
      ,[SCHEDSTART]
      ,[SCHEDFINISH]
      ,[CREWID]
      ,[FAILURECODE]
      ,[SITEID]
      ,[CLASSSTRUCTUREID]
      ,[F37]
      ,[Year]
      ,[SPARECOST]
      ,[LABORCOST]
      ,[IsReview]
      ,[DEV_WORKTYPE]
      ,[CMDowntime]
      ,[PMDowntime]
      ,[RMDowntime]
      ,[NONPPMDowntime]
      ,[LDTEXT] from [dbo].[client_workorder_PRD]
  

  select count(*) from [dbo].[Client_workorder_All]

  select Count(*) from [dbo].[Asset_Master_ALL]

  select * from [AX_Segment_Metric_Facts_All]

   insert into [dbo].[AX_Segment_Metric_Facts_All]
   select * from [dbo].[AX_Segment_Metric_Facts_PRD]


   select * into [dbo].[AX_Asset_Saving_All] from [AX_Asset_Saving_DAF]
   insert  into [dbo].[AX_Asset_Saving_All]
    select *  from [AX_Asset_Saving_PRD]

	select * from
	[AX_Asset_Saving_All]

GO


